name: class_extensions_annotations
version: 0.0.0
author: svarzee <svarzee@gmail.com>
homepage: https://github.com/svarzee/class_extensions
description: >-
  Annotations to use with class_extensions.
environment:
  sdk: '>=2.3.0 <3.0.0'
