builders:
  class_extensions:
    import: "package:class_extensions/builder.dart"
    builder_factories: ["classExtensionsBuilder"]
    build_extensions: {".dart": ["class_extensions.g.part"]}
    applies_builders: ["source_gen|combining_builder"]
    auto_apply: dependents
    build_to: cache

  dummy_extension_generators:
    import: "package:class_extensions/builder.dart"
    builder_factories: ["extensionStartDummyBuilder", "extensionEndDummyBuilder"]
    build_extensions: {".dart": []}